version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rag_chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: admin
      DB_NAME: rag_chatbot
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./uploads:/app/uploads

volumes:
  postgres_data: